# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'FitGoal' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for FitGoal
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit', '6.0.0', :modular_headers => true

  target 'FitGoalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitGoalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
